docs: add installation steps
graasp/graasp-research pull request #141
Opened 2023-04-25 09:04 UTC by rayacers

2023-04-28 08:41 UTC, spaenleh requested changes
looks good, thank you for the documentation ! Much need 😅  Please have a look at my comments, integrate the ones that make sense to you.

2023-04-28 08:41 UTC, spaenleh commented on README.md
> +REACT_APP_GRAASP_PERFORM_HOST = http://localhost:3112
```suggestion
REACT_APP_GRAASP_PERFORM_HOST=http://localhost:3112
```

2023-04-28 08:41 UTC, spaenleh commented on README.md
> +REACT_APP_HIDDEN_ITEM_TAG_ID=b5373e38-e89b-4dc7-b4b9-fd3601504467
Maybe add a comment that this should match the hidden tag id variable in the backend env file.

2023-04-28 08:41 UTC, spaenleh commented on README.md
> +4. Run yarn start. The client should be accessible at `localhost:3113`
```suggestion
4. Run `yarn start`. The client should be accessible at `localhost:3113`
```

2023-04-28 08:41 UTC, spaenleh commented on README.md
> +1. Run yarn to install the dependencies.
```suggestion
1. Run `yarn` to install the dependencies.
```

2023-04-28 08:41 UTC, spaenleh commented on README.md
> +2. Run the API at `localhost:3000`
Maybe here add a link to the graasp/graasp repo.
```suggestion
2. Run [the API](https://github.com/graasp/graasp) at `localhost:3000`
```

2023-04-28 08:41 UTC, spaenleh commented on README.md
> +3. Set the following environnement variables in `.env.local`
```suggestion
3. Set the following environnement variables in `.env.local` (place this file at your project root)
```

2023-04-28 08:41 UTC, spaenleh commented on README.md
>  ## Available Scripts
Remove this section. It is coming from the CRA template and is not very useful in this context.

2023-04-28 08:41 UTC, spaenleh commented on README.md
> +<img width="1381" alt="Screenshot 2023-04-27 at 4 58 43 PM" src="https://user-images.githubusercontent.com/13879502/234903339-a95ee2b8-a89e-4edb-a22a-20e9397346a6.png">
Maybe put this image also at the top, so it looks a bit more interesting when you arrive on the repo 😄

2023-05-01 14:00 UTC, pyphilia approved these changes
Thanks for the update! 🦓

2023-05-02 09:46 UTC, spaenleh approved these changes
👍

2023-05-02 10:01 UTC, merged